plot4<-function() {
        fileUrl<-"http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
        if(!file.exists("household_power_consumption.txt"))
                download.file(fileUrl, "power")
        unzip("power")
        data <- read.csv("household_power_consumption.txt", sep=";", nrows=2880, skip=66636)
        y<-paste(data[,1], data[,2], sep = " ")
        z<-data[,3:9]
        yorder<-strptime(y, format ="%d/%m/%Y %T")
        data<-cbind(yorder, z)
        png(file="plot4.png", width=480, height=480 )
        par(mfrow = c(2,2))
        plot(data[,1], data[,2], type="n", xlab="", ylab="Global Active Power (kilowatts)")
        lines(data[,1], data[,2])
        plot(data[,1], data[,4], type="n", xlab="datetime", ylab="Voltage")
        lines(data[,1], data[,4])
        plot(data[,1], data[,6], type="n", xlab="", ylab="Energy sub metering")
        lines(data[,1], data[,6])
        lines(data[,1], data[,7], col="red")
        lines(data[,1], data[,8], col="blue")
        legend("topright", col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1, 1, 1))
        plot(data[,1], data[,3], type="n", xlab="datetime", ylab="Global_reactive_power")
        lines(data[,1], data[,3])
        dev.off()
}